// Generated by BUCKLESCRIPT VERSION 4.0.8, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as ParseAndRenderCard$SimpleDeck from "./ParseAndRenderCard.bs.js";

var component = ReasonReact.statelessComponent("CardView");

function make(code, imageSource, flipped, onClick, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", {
                          className: flipped ? "Card flipped" : "Card",
                          onClick: onClick
                        }, React.createElement("div", {
                              className: "Card front"
                            }, React.createElement("img", {
                                  alt: ParseAndRenderCard$SimpleDeck.parseAndRender(code),
                                  src: imageSource
                                })), React.createElement("div", {
                              className: "Card back"
                            }));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var $$default = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.code, jsProps.imageSource, jsProps.flipped, jsProps.onClick, /* array */[]);
      }));

export {
  component ,
  make ,
  $$default ,
  $$default as default,
  
}
/* component Not a pure module */
